/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Amanda Marley
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegR = new javax.swing.JButton();
        RegCus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        RegE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegR.setBackground(new java.awt.Color(102, 102, 0));
        RegR.setForeground(new java.awt.Color(255, 255, 255));
        RegR.setText("REGISTER A REPAIR JOB");
        RegR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegRActionPerformed(evt);
            }
        });
        getContentPane().add(RegR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        RegCus.setBackground(new java.awt.Color(153, 153, 255));
        RegCus.setForeground(new java.awt.Color(255, 255, 255));
        RegCus.setText("REGISTER  CUSTOMER");
        RegCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCusActionPerformed(evt);
            }
        });
        getContentPane().add(RegCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK TO LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        RegE.setBackground(new java.awt.Color(0, 102, 102));
        RegE.setForeground(new java.awt.Color(255, 255, 255));
        RegE.setText("REGISTER AN EMPLOYEE");
        RegE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEActionPerformed(evt);
            }
        });
        getContentPane().add(RegE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("HOMEPAGE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Wallpaper/Background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCusActionPerformed
     CustomerRegistration bm=new CustomerRegistration();
        bm.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegCusActionPerformed

    private void RegEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEActionPerformed
        EmployeeRegistration bm=new EmployeeRegistration();
        bm.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegEActionPerformed

    private void RegRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegRActionPerformed
         RepairJobRegistration bm=new RepairJobRegistration();
        bm.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegRActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      LoginForm bm=new LoginForm();
        bm.setVisible(true);
        dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegCus;
    private javax.swing.JButton RegE;
    private javax.swing.JButton RegR;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
